version: "3.7"

services:
  blog:
    container_name: blog
    image: drakejin/blog:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command:
      - tail
      - -f
      - /dev/null
